# Generated by Django 3.1.7 on 2021-03-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=50)),
                ('bengali', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=1)),
                ('confidence', models.IntegerField(default=0)),
                ('next_review', models.DateField()),
                ('focus', models.DateField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dict_words', to='app.dictionary')),
            ],
        ),
    ]
