# Generated by Django 3.1.7 on 2021-02-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=50)),
                ('bengali', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=5)),
            ],
        ),
    ]
