# Generated by Django 3.1.7 on 2021-02-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vocabulary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dict_words', to='app.dictionary'),
        ),
    ]
