# Generated by Django 3.1.7 on 2022-06-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_gnome',
            field=models.BooleanField(default=False),
        ),
    ]
